spring:
  #  datasource:
  #    url: jdbc:h2:mem:example-app;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  #    platform: h2
  #    username: sa
  #    password:
  #    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update


ribbon:
  #  ReadTimeout: 60000
  #  connection-timeout: 3000
  eureka:
    enabled: false


learning-service:
  ribbon:
    listOfServers: ${DOCKER_HOST_IP:localhost}:8083

collector-service:
  ribbon:
    listOfServers: ${DOCKER_HOST_IP:localhost}:8082

validator-service:
  ribbon:
    listOfServers: ${DOCKER_HOST_IP:localhost}:8081
